config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'application#welcome'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/babies/:baby_id/events/new', to: 'events#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/search', to: 'events#search'
  resources :users
  resources :babies do
    resources :events
  end
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
    has_many :events
    has_many :users, through: :events

    validates :name, presence: true
    validates :DOB, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :baby
    belongs_to :user

    validates :content, presence: true
    validates :time, presence: true
    validates :baby_id, presence: true
      
    def self.latest_event
      order('time desc').first
    end

    def self.search(content)
        self.where('content LIKE ?', "%#{content}%")
    end
      
end

app/models/user.rb
class User < ApplicationRecord
    has_many :babies
    has_many :events, through: :babies 
    
    has_secure_password

    validates :email, presence: true, :uniqueness => { :case_sensitive => false }
    validates :password, length: { minimum: 6 }, if: :password_digest_changed?
    validates :name, presence: true
    validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper

    def welcome 
        if logged_in?
            redirect_to user_path(current_user.id)
        else
            render 'welcome'
        end
    end 
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  include BabiesHelper
  before_action :require_ownership, except: [:new, :create]
  before_action :set_baby, only: [:update, :edit, :destroy, :show]
    
    def index
      @babies = Baby.where(user_id: current_user.id)
    end
  
    def show
      @baby = Baby.find_by(params[:id])
    end
  
    def new
      @baby = Baby.new
    end
   
    def create
      @baby = current_user.babies.build(baby_params)
       if @baby.save
         redirect_to user_path(@baby.user_id) 
       else
        render :new
       end
    end

    def edit
      @baby = Baby.find(params[:id])
    end
  
    def update
      @baby = Baby.find(params[:id])
      if @baby.update(baby_params)
        redirect_to user_path(@baby.user_id)
      else 
        render :edit
      end 
    end
  
    def destroy
      @baby = Baby.find(params[:id])
      @baby.destroy
      redirect_to signup_path  
    end

    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :set_event, only: [:update, :destroy, :show]
  before_action :require_ownership, except: [:new, :create, :index, :search]
  def index
    if params[:baby_id]
      @events = Event.where(baby_id: params[:baby_id])
    else
    @events = Event.all
    end
    @events132 = Event.latest_event
  end
  
  def search
    results = Event.search(params[:content]) 
    @events = results.where(user_id: current_user.id)
  end 

  def show
    
  end

  def new 
    if params[:baby_id]
      @baby = Baby.find_by(id: params[:baby_id])
      @event = Event.new
    else 
      @event = Event.new
    end 
  end

  def create
    @event = Event.new(event_params)
    if @event.save 
      redirect_to user_path(current_user.id) 
    else 
    render :new
    end 
  end

  def edit
    if params[:baby_id]
      @event = Event.find(params[:baby_id])
    else
      set_event
    end
  end

  def update
    if @event.update(event_params)
      redirect_to user_path(@event.user_id)
    else 
      render :edit
    end 
  end

  def destroy
    @event.destroy
    redirect_to signup_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to user_path(current_user.id)
    end 
  end

  def create
       user = User.find_by(username: params[:username])
       if user && user.authenticate(params[:password])
         session[:user_id] = user.id
         redirect_to user_path(current_user.id)
       else 
         render :new
       end 
  end

  def destroy
    session.delete :user_id
    redirect_to '/'
  end

  def omniauth 
    user = User.find_or_create_by(uid: request.env['omniauth.auth'][:uid], provider: request.env['omniauth.auth'][:provider]) do |u|
      u.username = request.env['omniauth.auth'][:info][:first_name]
      u.email = request.env['omniauth.auth'][:info][:email]
      u.name = request.env['omniauth.auth'][:info][:first_name]
      u.password = SecureRandom.hex(15)
    end 
    if user.valid?
      session[:user_id] = user.id 
      redirect_to user_path(current_user.id)
    else
      redirect_to login_path 
    end 
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :require_login, except: [:new, :create]
  before_action :set_user, only: [:update, :edit, :destroy, :show]

    def index
      @users = User.all
    end
  
    def show 
      
    end
  
    def new 
      if !logged_in?
        @user = User.new
      else
        redirect_to user_path(current_user.id)
      end
    end
  
    def create 
      @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to user_path(@user.id) 
        else 
          flash[:errors] = @user.errors.full_messages
          render :new
        end 
    end

    def edit 
      
    end
  
    def update
      if @user.update(user_params)
        redirect_to user_path(@user)
      else 
        flash[:errors] = @user.errors.full_messages
        render :edit
      end 
    end
  
    def destroy
      @user_babies = @user.babies
      @user_events = @user.events
      @user_babies.destroy
      @user_events.destroy
      @user.destroy
      redirect_to signup_path
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user # memoization
        @current_user ||= User.find_by(id: session[:user_id])
    end 

    def logged_in?
        current_user
    end 
end

app/helpers/babies_helper.rb
module BabiesHelper
    def set_baby
        @baby = Baby.find(params[:id])
    end

    def baby_params
      params.require(:baby).permit(:name, :DOB, :user_id)
    end 
    
    def require_ownership
      if set_baby.user_id != current_user.id
        redirect_to user_path(@baby.user_id)
     end
    end
end

app/helpers/events_helper.rb
module EventsHelper
    def set_event
        @event = Event.find_by(params[:id])
    end

    def event_params
      params.require(:event).permit(:content, :time, :user_id, :baby_id, :content)
    end 

    def require_ownership
      if set_event.user_id != current_user.id
        redirect_to user_path(params[:id])
     end
    end

    def require_ownership_for_nested_route
      if current_user.id != params[:id].to_i
        redirect_to user_path(params[:id])
      end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def set_user
        @user = current_user
    end

    def user_params
      params.require(:user).permit(:name, :email, :username, :email, :password)
    end 

    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to login_path
      end
    end

end

app/views/application/welcome.html.erb
Welcome to baby app 
<%= link_to 'signup', signup_path %>

app/views/babies/_form.html.erb
<% if @baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@baby.errors.count, "error") %> prohibited this article from being saved:</h2>  
      <ul>
        <% @baby.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_with model: @baby do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :DOB %>
    <%= f.text_field :DOB %><br>
    <%= f.submit 'Add' %><br>
<% end %>

app/views/babies/edit.html.erb
<% if @baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@baby.errors.count, "error") %> prohibited this article from being saved:</h2>  
      <ul>
        <% @baby.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_with model: @baby do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :DOB %>
    <%= f.text_field :DOB %><br>
    <%= f.submit 'edit' %><br>
<% end %>

<%= link_to('delete', baby_path(@baby), method: 'delete') %>

app/views/babies/index.html.erb
<%@babies.each do |x|%>
    <%= x.name %>
<%end %>

app/views/babies/new.html.erb
<%= render partial: "form" %>

app/views/babies/show.html.erb
    <%= @baby.name %>
    <%= @baby.DOB %>

app/views/events/_events.html.erb
Parent Name: <%=@event.user.name %>
<br/>
Baby Name:<%= @event.baby.name %>
<br/>
Content:<%= @event.content %>
<br/>
Time:<%= @event.time %>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this article from being saved:</h2>  
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<% if @baby %>
    <h1><%= @baby.name %></h1>
<% else %> 
    <h1>Log an Event and create a new baby</h1>
<% end %> 

<%= form_with model: @event do |f| %>
    
    <%= f.label :content %>
    <%= f.text_field :content %><br>
    
    <%= f.label :Date %>
    <%= f.text_field :time %><br>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <% if @baby%> 
        <%= f.hidden_field :baby_id, value: @baby.id %>
    <% end %> 




    <%= f.submit 'Add' %><br>

<% end %>

app/views/events/edit.html.erb
<% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this article from being saved:</h2>  
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_with model: @event do |f| %>

    
    <%= f.label :content %>
    <%= f.text_field :content %><br>
    
    <%= f.label :Date %>
    <%= f.text_field :time %><br>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <% if @baby%> 
        <%= f.hidden_field :baby_id, value: @baby.id %>
    <% end %> 




    <%= f.submit 'Add' %><br>

<% end %>

app/views/events/index.html.erb
<%@events.each do |t|%>
 <%=t.content%>
 <%=t.time%>
 <%=t.id%>
 <br/>
<%end%>

app/views/events/new.html.erb
New event 
<%= render partial: "form" %>

app/views/events/search.html.erb
search results 
<% if @events.empty? %>
    looks like nothing matched your search try again
    <% else %>
        <% @events.each do |c| %>
        <%= c.content %>
        <%= c.time %>
    <% end %>
<% end %>


<%= link_to 'go back', user_path(current_user.id)%>

app/views/events/show.html.erb
<%= render partial: "events" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabyEvent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br/>
    <% if logged_in?%>
      <%= link_to('logout', logout_path, method: 'get') %>
      <% else %>
        <%= link_to('login', login_path, method: 'get') %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_errors.html.erb
<% if flash[:errors] %>
  <div id="error_explanation">
    <h2><%= pluralize(flash[:errors].count, "error") %> prohibited this from being saved:</h2>
    <ul>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %> 
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>  
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_with model: @user do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :username %>
    <%= f.text_field :username %><br>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.submit 'Sign Up' %><br>
   
<% end %>


<h3>create an account with google:</h3>
<%= button_to 'Google', '/auth/google_oauth2' %>

app/views/users/_profile.html.erb
<h1> You're profile: <%= @user.name %>  <h1>
<%= link_to('logout', logout_path, method: 'get') %>
<br />
<%= link_to('delete', user_path(@user), method: 'delete') %>
<br />
<%= link_to 'edit', edit_user_path(@user)%>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<%= link_to 'Add a new baby', new_baby_path%>
<br/>

app/views/users/_userbabies.html.erb
<% @user.babies.each do |b|%>
<br/>
    <%= b.name %> 
    <%= b.DOB %> <%= link_to 'edit', edit_baby_path(b)%>
        <% b.events.each do |a| %>
            <br/>
            <%= a.content %>
            <br/>
            <%= a.time %>
            <br/>
            <%= link_to 'edit event', edit_baby_event_path(a)%>
            <%= link_to('delete', event_path(a), method: 'delete') %>
            <br>
        <% end %>
        <br/>
    <%= link_to 'Log event', new_baby_event_path(b)%>
<% end %>

app/views/users/edit.html.erb
<h1>Edit yout account </h1>

<%= form_with model: @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :username %>
    <%= f.text_field :username %><br>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
    <%= f.hidden_field :password %><br>

    <%= f.submit 'Submit changes' %><br>
   
<% end %>

app/views/users/index.html.erb
<%=@users.each do |c|%>
<%= c.name %>
<% end %>

app/views/users/new.html.erb
<h1>Create a new user:</h1>

<%= render partial: "form" %>

app/views/users/show.html.erb
<%= render partial: "profile" %>
<%= render partial: "userbabies" %>
 <%= form_with url: search_path, method: :get do |f| %>
  <%= f.label :content, "Search Events by content:" %>
  <%= f.text_field :content %>
  <%= f.submit "Search"%>
<% end %>